FROM node:18-alpine

# Create an app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install Python 3, pip, and venv
RUN apk add --no-cache python3 py3-pip python3-dev build-base

# Create and activate a virtual environment
RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

# Copy the requirements.txt file and install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Download NLTK data packages
RUN python3 -m nltk.downloader punkt wordnet stopwords

# Copy frontend directory and other necessary files
COPY frontend /app/frontend
COPY SkLearnLinearRegression.py /app
COPY EstimateHealthcareAppointmentLengthGivenX-Sheet2.csv /app

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "start"]
